module GdDoc
  class Type
    CONTROLS = %w[
      Control
        BaseButton
          Button
          LinkButton
          TextureButton
        ColorRect
        Container
          AspectRatioContainer
          BoxContainer
            HBoxContainer
            VBoxContainer
          CenterContainer
          EditorProperty
          FlowContainer
            HFlowContainer
            VFlowContainer
          FoldableContainer
          GraphElement
            GraphFrame
            GraphNode
          GridContainer
            OpenXRBindingModifierEditor
            ScriptEditor
          MarginContainer
          PanelContainer
          ScrollContainer
            EditorInspector
          SplitContainer
            HSplitContainer
            VSplitContainer
          SubViewportContainer
          TabContainer
        GraphEdit
        ItemList
        Label
        LineEdit
        MenuBar
        NinePatchRect
        Panel
        Range
          EditorSpinSlider
          ProgressBar
          ScrollBar
            HScrollBar
            VScrollBar
          Slider
            HSlider
            VSlider
          SpinBox
          TextureProgressBar
        ReferenceRect
        RichTextLabel
        Separator
          HSeparator
          VSeparator
        TabBar
        TextEdit
          CodeEdit
        TextureRect
        Tree
        VideoStreamPlayer
      ]
  end
end

