
task :default => :all


task :all do
  sh 'bundle exec nanoc'
  sh 'bundle exec nanoc view --host 0.0.0.0 --port 3001'
end


task :watch do
  # WARNING: Not working on WSL
  trap :INT do
    pid = `pgrep -u #{Process.uid} -f puma`
    Process.kill(:TERM, pid.to_i) if pid
    exit
  end
  sh 'bundle exec nanoc live --host 0.0.0.0 --port 3001'
end
